import { BookingQuoteChargeBeanFull, makeRowId } from 'phoenix-common-react';

export const mapAccurateRateDetailBeanToRow = (
  bean: any,
  chargeDescEnglish: Record<string, string>,
  index: number
): BookingQuoteChargeBeanFull => ({
  incomeChargeDetails: {
    chargeCode: bean.chargeCode ?? '',
    chargeDescription: chargeDescEnglish?.[bean.chargeCode] ?? '',
    chargeType: bean.chargeType ?? 'OFR',
  },
  incomeRate: parseFloat(bean.chargeRate ?? '0') || 0,
  incomeCurrency: bean.currencyCode ?? '',
  incomeBasis: bean.rateBasis ?? '',
  incomeAmount: 0,
  incomeROE: 1,
  incomeLocalAmount: 0,
  incomeVAT: 'N',
  incomeOldBasis: '',
  incomeMaximumRate:
    bean.maximumRate != null ? parseFloat(bean.maximumRate) : null,
  incomeMinimumRate:
    bean.minimumRate != null ? parseFloat(bean.minimumRate) : null,
  incomeCFSFee: '',
  incomeOldBasisMinByKgCbm: '',

  expenseRate: 0,
  expenseCurrency: '',
  expenseBasis: '',
  expenseAmount: 0,
  expenseROE: 1,
  expenseLocalAmount: 0,
  expenseVAT: 'N',
  expenseOldBasis: '',
  expenseMaximumRate: null,
  expenseMinimumRate: null,
  expenseCFSFee: '',

  originDestination: ['OFR', 'FOB', 'OCC'].includes(bean.chargeType ?? '') ? 'O' : 'D',
  prepaidCollect: bean.prepaidCollect ?? '',
  vendor: '',
  vendorReference: '',
  invoiceNumber: '',
  invoiceDate: '',
  rateOfExchangeType: '',
  rowId: makeRowId(),
  equipmentDetails: '',
  numberOfContainer: 0,
  pnlExpense: 0,
  cfsFee: '',

  isLinkedWithPhoenix: false,
  rowSequence: index,
  relayFlag: 'A',
  isPrintOnDocument: true,
  transactionalFlag: 'N',
  isVatBean: false,
  isEnableForEdit: true,
  isFiltered: false,
  isZeroAllowed: true,
  isTruckingRates: false,
  additionalRatingFlags: {},
  transmittedFlag: '',

  actualLenght: bean.actualLenght ?? 0,
  fromLenght: bean.fromLenght ?? 0,
  actualWeight: bean.actualWeight ?? 0,
  fromWeight: bean.fromWeight ?? 0,

  isOldRate: false,
  isCalculatedZero: bean.calculatedZero ?? false,
  isOFRAccurate: true,
  isFileROE: false,

  vatPercent: '0',
  vatType: '',
  vatAmount: 0,
  taxKey: '',
  taxCode: '',
  taxText: '',
  applyFor: '',
  glCode: '',

  overridden: false,

  invoiceCurrency: '',
  invoiceCurrencyROE: 0,
  invoiceCurrencyTotalAmount: 0,
  invoiceSellRateOfExchange: 0,
  invoiceExpenseRateOfExchange: 0,
  invoiceSellAmount: 0,
  invoiceExpenseAmount: 0,
  invToLocalCurrencyROE: 0,
  invoiceCurrencyROEViewOnly: 0,
  invToLocalCurrencyROEViewOnly: 0,

  userDefineChargeDescription: '',

  measureFrom: bean.measureFrom ?? '',
  measureTo: bean.measureTo ?? '',
  aspect: bean.aspectSeparatedByComma ?? '',

  companyId: bean.companyId ?? '',
  bookingRateId: String(bean.rateDetailId ?? ''),
  truckingChargeLinkId: 0,
  rateCompanyId: 0,
  lotRateId: '',

  spotRateDetailsId: bean.spotRateDetailsId ?? '',
  rateDetailId: String(bean.rateDetailId ?? ''),
  spotRateKey: '',
  spotRateFlag: bean.spotRateFlag ?? 1,
  spotRateEfftectiveDate: '',
  ExpirationDate: '',
  accurateSpotRateKey: '',
  isChargeRest: false,
  sprKey: '',

  fmcChargeType: 'Y',
  tabNumber: 0,
  bookingType: '',
  isAdditionalInvCharge: '',
  oinvoiceNumber: '',
  isNewlyAddedRow: true,
  isFocusSet: false,
  rateTypeFlag: bean.standardFlag ?? 0,
  isCallFromAccurate: true,
  isFirstTimeRatesAdded: null,
  taxAmount: null,
  taxLocalAmount: null,

  truckerRateExpired: '',
  truckChargeGroup: '',
  truckCity: '',
  truckZipCountry: '',
  truckChargeNotes: '',
  truckerName: '',
  truckRateId: 0,
  cfsName: '',
  doorCountry: '',
  euVatRuleId: 0,
  pickupId: '',
  expensePickupId: '',
  truckRate: {},
  truckRateDetailsFileId: 0,
});
