export interface AccurateRateRequestBean {
  placeOfReceiptCode: string | null;
  loadCode: string | null;
  dischargeCode: string | null;
  deconsolidationCode: string | null;
  finalCfsCode: string | null;
  placeOfDeliveryCode: string | null;
  originInlandCFSCode: string | null;
  consolidationCFSCode: string | null;
  portOfLoadingCode: string | null;
  transhipment1Code: string | null;
  transhipment2Code: string | null;
  transhipment3Code: string | null;
  portOfDischargeCode: string | null;
  deconsolidationCFSCode: string | null;
  destinationCFSCode: string | null;
  originOfRequest: string | null;
  companyCode: string | null;
  namedAccountCode: string | null;
  cubeCargo: number;
  weightCargo: number;
  prepaidCollect: string | null;
  uomValue: string | null;
  overLengthFlag: boolean;
  overWeightFlag: boolean;
  hazardousFlag: boolean;
  dimensionBeans: unknown | null;
  companyId: string | null;
  rateProfileCode: string | null;
  shipmentDate: string | null;
  locale: string | null;
  controllingEntity: string | null;
  rateControllingEntity: string | null;
  module: string | null;
  cubeCargoInFeet: number;
  destinationCFSNamedAccount: string | null;
  dischargeNamedAccount: string | null;
  officeId: number | null;
  officeCode: string | null;
  spotRateFlag: number;
  ratingType: string | null;
  direction: string | null;
  tabNumber: number;
  nacRatesAvailable: boolean;
  nonStackable: unknown | null;
  aspects: string | null;
  terms: string | null;
  pickupDeliveryFlag: string | null;
}

export interface AccurateRateDetailBean {
  rateDetailId: string | null;
  companyId: string | null;
  companyCode: string | null;
  namedAccountId: string | null;
  namedAccountCode: string | null;
  customerAliasId: string | null;
  customerAliasCode: string | null;
  placeOfReceiptCode: string | null;
  loadCode: string | null;
  dischargeCode: string | null;
  deconsolidationCode: string | null;
  finalCfsCode: string | null;
  placeOfDeliveryCode: string | null;
  chargeType: string | null;
  chargeCode: string | null;
  currencyCode: string | null;
  chargeRate: string | null;
  rateBasis: string | null;
  minimumRate: string | null;
  maximumRate: string | null;
  unitOfMeasurement: string | null;
  measureFrom: string | null;
  measureTo: string | null;
  effectiveDate: string | null;
  expirationDate: string | null;
  prepaidCollect: string | null;
  comments: string | null;
  status: string | null;
  inputLdapUser: string | null;
  inputOfficeId: string | null;
  inputDate: string | null;
  updateLdapUser: string | null;
  updateOfficeId: string | null;
  updateDate: string | null;
  transactionId: string | null;
  locked: unknown | null;
  aspectSeparatedByComma: string | null;
  actualLenght: number;
  fromLenght: number;
  actualWeight: number;
  fromWeight: number;
  originInlandCFSCode: string | null;
  consolidationCFSCode: string | null;
  portOfLoadingCode: string | null;
  transhipment1Code: string | null;
  transhipment2Code: string | null;
  transhipment3Code: string | null;
  portOfDischargeCode: string | null;
  deconsolidationCFSCode: string | null;
  destinationCFSCode: string | null;
  originOfRequest: string | null;
  routingKey: string | null;
  controllingEntity: string | null;
  standardFlag: number;
  spotRateDetailsId: string | null;
  spotRateFlag: number;
  spotRateDetails: unknown | null;
  conditionalMandatoryType: string | null;
  originDestinationKey: string | null;
  calculatedZero: boolean;
}

export interface AccurateRateResponseBean {
  rateDetailBeans: AccurateRateDetailBean[];
  chargeDescEnglish: Record<string, string>;
  chargeDescLocale: Record<string, string>;
  nacRatesAvailable: boolean;
}
