export interface SendDocumentMainBean {
    stackName?: string;
    isStackOpen?: boolean;
    fromName?: string;
    fromEmail?: string;
    subject?: string;
    body?: string;
    toEmails?: Record<string, string>;
    ccEmails?: Record<string, string>;
    bccEmails?: Record<string, string>;
    fromEmails?: Record<string, string>;
    isMergeDocumentsCheckBoxRequired?: boolean;
    isIncludeNoteCheckBoxRequire?: boolean;
    isMergeDocumentsCheckBoxSelected?: boolean;
    isIncludeNoteCheckBoxSelected?: boolean;
    // documentAttachedBeans?: DocumentAttachedBean[];
    // documentPackageBeans?: DocumentPackageBean[];
    // toggleImage?: string;
    referenceNumber?: string;
    shipmentDirection?: string;
    documentCode?: string;
    moduleCode?: string;
    // toggleButtonsMap?: Record<string, string>;
    isShowDesignFromEmail?: boolean;
    receiverName?: string;
    telePhoneNumber?: string;
    emailBodyTemplate?: string;
    preadviceemailBodyTemplate?: string;
    isShowPreadviceEmail?: boolean;
    officeName?: string;
    officeAddress?: string;
    isFromImportPayment?: boolean;
    releaseOrderBodyTemplate?: string;
    showReleaseOrderEmail?: boolean;
    isAttachFromEdocs?: boolean;
    referenceNumber1?: string;
    cfsR?: string;
    isShowTransmitToCargoesFlowBtn?: boolean;
    isImportStatusUpdate?: boolean;
    isContainerStatusUpdate?: boolean;
    isProofOfDelivery?: boolean;
}