declare module 'phoenix-common-react' {
  export type AccessoriesOption = any;
  export type BookingFormState = any;
  export type BookingQuoteChargeBeanFull = any;
  export type BookingQuoteResponse = any;
  export type CancelBookingApiResponse = any;
  export type CancelBookingRequestData = any;
  export type CargoFlagsType = any;
  export type CargoMetrics = any;
  export type CargoRowType = any;
  export type CustomDetailsFormData = any;
  export type DimensionChangePayload = any;
  export type DimensionRowType = any;
  export type DocumentUploadFormData = any;
  export type EoriPortConditions = any;
  export type FlagHandlers = any;
  export type FlagState = any;
  export type LCLFormState = any;
  export type LocationInformationData = any;
  export type LoginClientBeanRaw = any;
  export type LotRowData = any;
  export type MultiPanelSuggestionItem = any;
  export type RateDetailsFormData = any;
  export type RateRequestBean = any;
  export type RoeRow = any;
  export type RoutingFormData = any;
  export type ScheduleGroup = any;
  export type ScheduleRow = any;
  export type ChargeDetails = any;
  export type CommonRateDetails = any;
  export type CommonRateOfExchange = any;
  export type ContainerValidationRecord = any;
  export type FetchTmsButtonState = any;
  export type GenAesFilingBean = any;
  export type GetRateQuoteInputBean = any;
  export type StatusType = any;
  export type TaxBean = any;
  export type TaxInfo = any;
  export type ToggleKey = any;
  export type TmsBookingContext = any;
  export type TmsCarrierQuoteResult = any;
  export type TmsCommodityBean = any;

  export const API_ENDPOINTS: any;
  export const ApiService: {
    get<TResponse = any>(
      url: string,
      config?: any
    ): Promise<{ data: TResponse } & any>;
    post<TResponse = any>(
      url: string,
      data?: any,
      config?: any
    ): Promise<{ data: TResponse } & any>;
    put<TResponse = any>(
      url: string,
      data?: any,
      config?: any
    ): Promise<{ data: TResponse } & any>;
    delete<TResponse = any>(
      url: string,
      config?: any
    ): Promise<{ data: TResponse } & any>;
  };
  export const APPLICATION_URL: string;
  export const WEB_SERVICE_URL: string;
  export const COMMON_WEB_SERVICE_URL: string;
  export const WEB_SERVICE_URL_FOR_OCEAN: string;
  export const PHOENIX_BASE_URL: string;
  export const COMMON_ENDPOINTS: any;
  export const PHOENIX_ENDPOINTS: any;
  export const WEB_SERVICE_ENDPOINTS: any;
  export const BookingMainDetailsSection: any;
  export const CargoDetails: any;
  export const CommonToggleKeys: any;
  export const CustomDetails: any;
  export const CustomerDetails: any;
  export const FillingDetails: any;
  export type FillingDetailsFormData = any;
  export const initialFillingDetailsFormData: any;
  export const filingByListBoxConfig: (moduleName: string, officeId: string) => any;
  export const DocumentDetails: any;
  export const DocumentStatusIcons: any;
  export const FeatureToggleInitializer: any;
  export const GwtBridge: any;
  export const IRPPopup: any;
  export const LocationInformation: any;
  export const PModal: any;
  export const PreBookingMainDetails: any;
  export const PreBookingRoutingDetailsPage: any;
  export const QuoteMainDetails: any;
  export const RateDetails: any;
  export const RateDetailsIcons: any;
  export const RoutingDetails: any;
  export const TermsAndConditions: any;
  export const ToolBar: any;
  export const YiYunCfsIntegrationDetails: any;
  export const bookingReducer: any;
  export const buildBookingQuoteCargoBean: any;
  export const buildBookingQuoteChargeBeanList: any;
  export const buildBookingQuoteCustomerBean: any;
  export const buildImportBookingQuoteCustomerBean: any;
  export const buildBookingQuoteMultiCargoBeanList: any;
  export const buildBookingQuoteRoutingBean: any;
  export const buildDoorDeliveryDetailsBean: any;
  export const buildMultiCargoBookingQuoteNoteBeans: any;
  export const buildMultiplePickupDetailBeanList: any;
  export const buildPickupDetailBean: any;
  export const buildTransshipmentRoutingBeanList: any;
  export const calculateMultipleVat: any;
  export const calculateVatForEachRateRow: any;
  export const commodityListBoxConfig: any;
  export const createDefaultDocumentRows: any;
  export const createDefaultMainDetailsState: any;
  export const featureToggleReducer: any;
  export const gwtBridgeInstance: any;
  export const initialCustomDetailsValue: any;
  export const loginClientBeanReducer: any;
  export const mapBookingQuoteBeanToMainDetails: any;
  export const mapCargoFromPopulate: any;
  export const mapCustomerFromPopulate: any;
  export const mapCustomFromPopulate: any;
  export const mapDocumentDetailsToUploadDocumentBeans: any;
  export const mapMainDetailsToBookingQuoteBean: any;
  export const mapMainDetailsToPreBookingQuoteBean: any;
  export const mapRateDetailsFromPopulate: any;
  export const mapPickupChargeBeansToRateRows: any;
  export interface PickupTruckerInfo {
    truckerName?: string;
    truckCity?: string;
    truckZipCountry?: string;
  }
  export const mapPickupChargesToRateRows: (
    charges: any[],
    pickupId: number,
    localCurrency?: string,
    truckerInfo?: PickupTruckerInfo
  ) => any[];
  export const mapDoorDeliveryChargesToRateRows: (
    charges: any[],
    localCurrency?: string,
    truckerInfo?: PickupTruckerInfo
  ) => any[];
  export const mapRoutingFromPopulate: any;
  export const mapTruckingFromPopulate: any;
  export const mapUploadDocumentBeansToDocumentDetails: any;
  export const pickupACCESSORIALS: any;
  export const tmsShipmentStatusConfig: (moduleCode: string) => any;
  export const deliveryACCESSORIALS : any;
  export type MilestoneStep = {
    label: string;
    isActive?: boolean;
    activeDate?: string;
    activeTime?: string;
  };
  export type ShipmentStatusInputBean = {
    shipmentIDs: string[];
    moduleCode: string;
  };
  export type ShipmentActivityHistoryBean = {
    activityDescription: string;
    activityDate: string;
  };
  export type ShipmentStatusResultBean = {
    activityHistory: ShipmentActivityHistoryBean[];
  };
  export const preBookingReducer: any;
  export const quoteBookingReducer: any;
  export const resetBookingForm: any;
  export const formatDate: any;
  export const formatTime: any;
  export const getLongDateTimeFormat: any;
  export const num: any;
  export const pickupCargoAtcodeSuggestionConfig: any;
  export const selectOfficeId: any;
  export const setArTaxBeanMap: any;
  export const setReferenceDisabled: any;
  export const str: any;
  export const strOrNull: any;
  export const useContainerValidation: any;
  export const VAT_CHARGE_CODE: any;
  export const updateBookingDocumentDetails: any;
  export const updateBookingMainDetails: any;
  export const updatePreBookingMainDetails: any;
   export const updateCustomerType: any;

  export const useAppSelector: any;
  export const useFeatureToggle: any;
  export const useGetSelections: any;
  export const useIRPController: any;
  export const useStackProgressBar: any;
  export const useTabId: any;
  export type buildStateSuggestionConfig = any;
  export const buildStateSuggestionConfig: any;
  export type buildTmsCargoDetails = any;
  export const buildTmsCargoDetails: any;
  export type CargoDetailsFormData = any;
  export const CargoDetailsFormData: any;
  export type CargoRow = any;
  export const CargoRow: any;
  export type CargoRowsHandlers = any;
  export const CargoRowsHandlers: any;
  export type CargoRowsState = any;
  export const CargoRowsState: any;
  export type carrierCodeSuggestionConfig = any;
  export const carrierCodeSuggestionConfig: any;
  export type CarrierMainDetails = any;
  export const CarrierMainDetails: any;
  export type CarrierOptionsFormData = any;
  export const CarrierOptionsFormData: any;
  export type CarrierOptionsModal = any;
  export const CarrierOptionsModal: any;
  export type CarrierQuote = any;
  export const CarrierQuote: any;
  export type CbmDialogHandlers = any;
  export const CbmDialogHandlers: any;
  export type CbmDialogState = any;
  export const CbmDialogState: any;
  export type ChargesState = any;
  export const ChargesState: any;
  export type ChargeType = any;
  export const ChargeType: any;
  export type ContainerDimensionRecord = any;
  export const ContainerDimensionRecord: any;
  export type countrySuggestionConfig = any;
  export const countrySuggestionConfig: any;
  export type createBlankBeanRow = any;
  export const createBlankBeanRow: any;
  export type createBlankRoeRow = any;
  export const createBlankRoeRow: any;
  export type CustomerDetailFormState = any;
  export const CustomerDetailFormState: any;
  export type CustomerFormData = any;
  export const CustomerFormData: any;
  export type CustomerMoreDetailsForm = any;
  export const CustomerMoreDetailsForm: any;
  export type CustomsRowsHandlers = any;
  export const CustomsRowsHandlers: any;
  export type CustomsRowsState = any;
  export const CustomsRowsState: any;
  export type DEFAULT_PICKUP_FORM = any;
  export const DEFAULT_PICKUP_FORM: any;
  export type defaultPickupDeliveryFormData = any;
  export const defaultPickupDeliveryFormData: any;
  export type defaultRateDetailsFormData = any;
  export const defaultRateDetailsFormData: any;
  export type defaultTruckerFormData = any;
  export const defaultTruckerFormData: any;
  export type DimRowData = any;
  export const DimRowData: any;
  export type DocumentStatusIcon = any;
  export const DocumentStatusIcon: any;
  export type DOOR_DELIVERY_ACCESSORIALS = any;
  export const DOOR_DELIVERY_ACCESSORIALS: any;
  export type DoorDeliveryFormData = any;
  export const DoorDeliveryFormData: any;
  export type extractCountryCode = any;
  export const extractCountryCode: any;
  export type findByUnlocationCode = any;
  export const findByUnlocationCode: any;
  export type FormState = any;
  export const FormState: any;
  export type GetCurrencyConversionRateRequest = any;
  export const GetCurrencyConversionRateRequest: any;
  export type GetCurrencyConversionRateResponse = any;
  export const GetCurrencyConversionRateResponse: any;
  export type getInitialDoorDeliveryData = any;
  export const getInitialDoorDeliveryData: any;
  export type getInitialPreBookingFormData = any;
  export const getInitialPreBookingFormData: any;
  export type getInitialRoutingData = any;
  export const getInitialRoutingData: any;
  export type GetRateCalcWithFormulaRequest = any;
  export const GetRateCalcWithFormulaRequest: any;
  export type GetRateCalcWithFormulaResponse = any;
  export const GetRateCalcWithFormulaResponse: any;
  export type hazardousListBoxConfig = any;
  export const hazardousListBoxConfig: any;
  export type HazardousRowType = any;
  export const HazardousRowType: any;
  export type HazRowData = any;
  export const HazRowData: any;
  export type HeaderData = any;
  export const HeaderData: any;
  export type imoClassSelectionConfig = any;
  export const imoClassSelectionConfig: any;
  export type initialCargoRow = any;
  export const initialCargoRow: any;
  export type initialCarrierOptionsFormData = any;
  export const initialCarrierOptionsFormData: any;
  export type initialCustomerDetailFormState = any;
  export const initialCustomerDetailFormState: any;
  export type initialDimRow = any;
  export const initialDimRow: any;
  export type initialFlags = any;
  export const initialFlags: any;
  export type initialHazRow = any;
  export const initialHazRow: any;
  export type initialLotRow = any;
  export const initialLotRow: any;
  export type InstructionHandlers = any;
  export const InstructionHandlers: any;
  export type InstructionState = any;
  export const InstructionState: any;
  export type InternalCargoRowData = any;
  export const InternalCargoRowData: any;
  export type LclBookingDetailsForm = any;
  export const LclBookingDetailsForm: any;
  export type LCLRoutingPage = any;
  export const LCLRoutingPage: any;
  export type LclToggleKeys = any;
  export const LclToggleKeys: any;
  export type localStorageHelper = any;
  export const localStorageHelper: any;
  export type locationSuggestionConfig = any;
  export const locationSuggestionConfig: any;
  export type tmsLocationCodeSuggestionConfig = any;
  export const tmsLocationCodeSuggestionConfig: any;
  export type LotHandlers = any;
  export const LotHandlers: any;
  export type LotState = any;
  export const LotState: any;
  export type MainDetailsFormPayload = any;
  export const MainDetailsFormPayload: any;
  export type MainDetailsSection = any;
  export const MainDetailsSection: any;
  export type makeDefaultRow = any;
  export const makeDefaultRow: any;
  export type makeEmptyCargoRow = any;
  export const makeEmptyCargoRow: any;
  export type makeRowId = any;
  export const makeRowId: any;
  export type MODULE_BKG = any;
  export const MODULE_BKG: any;
  export type MODULE_QUO = any;
  export const MODULE_QUO: any;
  export type MODULE_PREBKG = any;
  export const MODULE_PREBKG: any;
  export const MODULE_BOL: any;
  export type MODULE_BOL = any;
  export const MODULE_ARN: any;
  export type MODULE_ARN = any;
  export type OceanToggleKeys = any;
  export const OceanToggleKeys: any;
  export type OrgCodeSuggestionItem = any;
  export const OrgCodeSuggestionItem: any;
  export type OriginDestination = any;
  export const OriginDestination: any;
  export type packagingSelectionConfig = any;
  export const packagingSelectionConfig: any;
  export type PICKUP_CARGO_ORG_DATA = any;
  export const PICKUP_CARGO_ORG_DATA: any;
  export type PickupCharge = any;
  export const PickupCharge: any;
  export type PickupChargesSection = any;
  export const PickupChargesSection: any;
  export type PickupDeliveryDetailsPanel = any;
  export const PickupDeliveryDetailsPanel: any;
  export type PickupDeliveryFormData = any;
  export const PickupDeliveryFormData: any;
  export type PickupDetailsFormData = any;
  export const PickupDetailsFormData: any;
  export type PreBookingCustomerDetail = any;
  export const PreBookingCustomerDetail: any;
  export type PreBookingFormData = any;
  export const PreBookingFormData: any;
  export type PrepaidCollect = any;
  export const PrepaidCollect: any;
  export type RateBasisUtility = any;
  export const RateBasisUtility: any;
  export type RateCalculationInput = any;
  export const RateCalculationInput: any;
  export type RateDetailsIcon = any;
  export const RateDetailsIcon: any;
  export type RelayFlag = any;
  export const RelayFlag: any;
  export type resetForm = any;
  export const resetForm: any;
  export type selectOfficeCode = any;
  export const selectOfficeCode: any;
  export type selectRaw = any;
  export const selectRaw: any;
  export type SHIPMENT_TYPE_OPTIONS = any;
  export const SHIPMENT_TYPE_OPTIONS: any;
  export type StandardDimensionPreset = any;
  export const StandardDimensionPreset: any;
  export type termsSuggestionConfig = any;
  export const termsSuggestionConfig: any;
  export type TRUCK_BOOKING_AUTO_FETCH_RATES = any;
  export const TRUCK_BOOKING_AUTO_FETCH_RATES: any;
  export type TruckerDetailsPanel = any;
  export const TruckerDetailsPanel: any;
  export type TruckerFormData = any;
  export const TruckerFormData: any;
  export type TruckerOptionsModal = any;
  export const TruckerOptionsModal: any;
  export type TruckingDetails = any;
  export const TruckingDetails: any;
  export type TruckRateV1 = any;
  export const TruckRateV1: any;
  export type updateCargoDetails = any;
  export const updateCargoDetails: any;
  export type updateLocationInformation = any;
  export const updateLocationInformation: any;
  export type updateMainDetails = any;
  export const updateMainDetails: any;
  export type printerSuggestionConfig = any;
  export const printerSuggestionConfig: any;
  export type useApi = any;
  export function useApi<TRequest = any, TResponse = any>(
    options: any
  ): {
    data: TResponse | null;
    execute: (payload?: TRequest) => Promise<TResponse>;
    isLoading: boolean;
    error: unknown;
  };
  export type useContainerDimensions = any;
  export const useContainerDimensions: any;
  export type useGetListBox = any;
  export const useGetListBox: any;
  export type useGetMultiPanelSuggestions = any;
  export const useGetMultiPanelSuggestions: any;
  export type useGetSuggestions = any;
  export const useGetSuggestions: any;
  export type useLocationData = any;
  export const useLocationData: any;
  export type useLocationInformation = any;
  export const useLocationInformation: any;
  export type useTermsAndConditionsApi = any;
  export const useTermsAndConditionsApi: any;
  export type vesselCodeSuggestionConfig = any;
  export const vesselCodeSuggestionConfig: any;
  export const CfsCargoRow: any;
  export const YiyunCfsIntegrationDetails: any;
  export const resetPreBookingForm: any;
  export const setReferenceNoInvalid: any;
  export const setImportQuoteNoInvalid: any;
  export type alternateGatewaySelectionConfig = any;
  export const alternateGatewaySelectionConfig: any;
  export type deliveryAlternateGatewaySelectionConfig = any;
  export const deliveryAlternateGatewaySelectionConfig: any;
  export type BookWithTmsResult = any;
  export type RefreshOptionsParams = any;
  export type RefreshOptionsResult = any;
  export const processVersioning: any;
  export const bookingVersionReducer: any;
  export type RefreshOptionsResult = any;
  export type ORIGIN_CODE = any;
  export const ORIGIN_CODE: any;
  export type WarehouseDetailsBean=any;
  export const WarehouseDetailsBean: any;
  export type data= any;
  export const data: any;
  export type TruckRateRequestBean= any;
  export const TruckRateRequestBean: any;
  export const FCLQuoteRoutingDetails: any;
  export type FCLTruckerFormData = any;
  export type FCLChargeItem = any;
  export const getInitialFCLTruckingData: any;
  export const FCLTruckingDetails: any;
  export type fclQuotePickupAndTruckerCodeSuggestionConfig = any;
  export const fclQuotePickupAndTruckerCodeSuggestionConfig: any;
  export type timeSuggestionConfig = any;
  export const timeSuggestionConfig: any;
  export type fclQuoteChargeDescriptionSuggestionConfig = any;
  export const fclQuoteChargeDescriptionSuggestionConfig: any;
  export type handlingCurrencySuggestionConfig = any;
  export const handlingCurrencySuggestionConfig: any;
  export const mapFCLTruckingFromPopulate: any;
  export type SelectOption = any;
  export type RateDetailsState = any;
  export type ContainerDataBean = any;
  export type ContainerTypeList = any;
  export const containerTypeSelectionConfig: any;
  export const FCLhazardousListBoxConfigType: any;
  export const useContainerDataBeanApi: any;
  export type RoutingRefs = any;
  export const CopyModal: any;
  export const quoteReferenceSuggestionConfig: any;
  export type CommodityPayload = any;
  export const RELAY_FLAG_ACCURATE: any;
  export const RELAY_FLAG_GRDB: any;
  export const RELAY_FLAG_MANUAL: any;
  export const RELAY_FLAG_CTC: any;
  export const RELAY_FLAG_TARRIF: any;
  export const RELAY_FLAG_IMPORT: any;
  export const RELAY_FLAG_TRK: any;
  export type BookingClauseBean = any;
  export type Clause = any;
  export type MinifiedLoginClientBean = any;
  export const FilingDetails: any;
}
