import type {
  CustomerDetailFormState,
  CustomerFormData,
  CustomerMoreDetailsForm,
  LclBookingDetailsForm,
} from '../../types/LCL/misc/CustomerDetails.types';

export const initialCustomerFormData: CustomerFormData = {
  customerCode: '',
  customerName: '',
  customerAddress: '',
  customerCity: '',
  customerState: '',
  customerStateId: '',
  customerStateName: '',
  customerZipCode: '',
  customerCountry: '',
  customerFax: '',
  customerType: '',
  customersContactName: '',
  salesRepresentative: '',
  telephoneNumber: '',
  mobileNumber: '',
  customerEmail: '',
  customerReference: '',
  truckSellRateProfile: '',
};

export const initialLclBookingDetailsForm: LclBookingDetailsForm = {
  customerCode: '',
  customerName: '',
  customerAddress: '',
  customerCity: '',
  customerState: '',
  customerStateId: '',
  customerStateName: '',
  customerZipCode: '',
  customerCountry: '',
  customerFax: '',
  customerType: '',
  customersContactName: '',
  salesRepresentative: '',
  telephoneNumber: '',
  mobileNumber: '',
  customerEmail: '',
  customerReference: '',
  truckSellRateProfile: '',
  accuRateProfile: '',
  prepaidCollect: '',
  controllingEntity: 'ORG',
  rateControllingEntity: 'ORG',
  agentName: '',
  agentEmail: '',
  asAgentFor: '',
  customerIt: '',
  customerEoriNumber: '',
  customerNamedAccount: '',
  namedAccount: '',
  // Shipper Details
  shipperName: '',
  shipperAddress: '',
  shipperEmail: '',
  shipperContactName: '',
  shipperReference: '',
  shipperPhoneNumber: '',

  // Consignee Details
  consigneeName: '',
  consigneeAddress: '',
  consigneeEmail: '',
  consigneeContactName: '',
  consigneeReference: '',
  consigneePhoneNumber: '',

  // Notify Party Details
  notifyPartyName: '',
  notifyPartyAddress: '',
  notifyPartyEmail: '',
  notifyPartyContactName: '',
  notifyPartyReference: '',
  notifyPartyPhoneNumber: '',
};

export const initialCustomerMoreDetailsData: CustomerMoreDetailsForm = {
  shipperCode: '',
  shipperNamedAccount: '',
  shipperName: '',
  shipperAddress: '',
  shipperCity: '',
  shipperState: '',
  shipperStateId: '',
  shipperStateName: '',
  shipperZipCode: '',
  shipperCountry: '',
  shipperContactName: '',
  shipperPhoneNumber: '',
  shipperEmail: '',
  shipperFax: '',
  shipperReference: '',
  shipperEoriNumber: '',
  shipperFmcLicensed: '',

  forwarderCode: '',
  forwarderNamedAccount: '',
  forwarderName: '',
  forwarderAddress: '',
  forwarderCity: '',
  forwarderState: '',
  forwarderStateId: '',
  forwarderStateName: '',
  forwarderZipCode: '',
  forwarderCountry: '',
  forwarderContactName: '',
  forwarderPhoneNumber: '',
  forwarderEmail: '',
  forwarderFax: '',
  forwarderReference: '',
  forwarderEoriNumber: '',
  forwarderFmcLicensed: '',

  purchaseOrder: '',

  consigneeCode: '',
  consigneeNamedAccount: '',
  consigneeName: '',
  consigneeAddress: '',
  consigneeCity: '',
  consigneeState: '',
  consigneeStateId: '',
  consigneeStateName: '',
  consigneeZipCode: '',
  consigneeCountry: '',
  consigneeContactName: '',
  consigneePhoneNumber: '',
  consigneeEmail: '',
  consigneeFax: '',
  consigneeReference: '',
  consigneeEoriNumber: '',
  consigneeFmcLicensed: '',

  notifyPartyCode: '',
  notifyPartyNamedAccount: '',
  notifyPartyName: '',
  notifyPartyAddress: '',
  notifyPartyCity: '',
  notifyPartyState: '',
  notifyStateId: '',
  notifyStateName: '',
  notifyPartyZipCode: '',
  notifyPartyCountry: '',
  notifyPartyContactName: '',
  notifyPartyPhoneNumber: '',
  notifyPartyEmail: '',
  notifyPartyFax: '',
  notifyPartyReference: '',
  notifyPartyEoriNumber: '',
  notifyPartyFmcLicensed: '',

  trackingCode: '',
  wwaReference: '',
  wwaCustomer: '',
};

export const initialCustomerDetailFormState: CustomerDetailFormState = {
  defaultForm: initialCustomerFormData,
  lclForm: initialLclBookingDetailsForm,
  customerMoreDetails: initialCustomerMoreDetailsData,
};
