import {
  RoutingFormData,
  AccessoriesOption,
  PickupDetailsFormData,
} from '../../types/LCL/routing/RoutingDetails.types';
import type { DoorDeliveryFormData } from '../../types/LCL/misc/TruckingDetails.types';

export const getInitialRoutingData = (): RoutingFormData => ({
  agentName: '',
  shipmentDate:'',
  agentEmail: '',
  terms: '',
  termsLabel: '',
  pickupNeeded: 'N',
  preCarriageType: '',
  preCarriageBy: '',
  preCarriageEts: null,
  vesselCode: '',
  vesselName: '',
  voyage: '',
  carrierCode: '',
  placeOfReceiptCode: '',
  placeOfReceiptUnCode: '',
  placeOfReceiptName: '',
  placeOfReceiptEtd: null,
  placeOfReceiptRegion: '',
  consolidationCfsCode: '',
  consolidationCfsUnCode: '',
  consolidationCfsName: '',
  consolidationCfsEtd: null,
  consolidationCfsRegion: '',
  portOfLoadingCode: '',
  portOfLoadingUnCode: '',
  portOfLoadingName: '',
  portOfLoadingEts: null,
  portOfLoadingRegion: '',

  transshipmentPorts: [{ id: 1, portCode: '', portName: '', eta: null }],

  portOfDischargeCode: '',
  portOfDischargeUnCode: '',
  portOfDischargeName: '',
  portOfDischargeEta: null,
  portOfDischargeRegion: '',

  deconsolidationCfsCode: '',
  deconsolidationCfsUnCode: '',
  deconsolidationCfsName: '',
  deconsolidationCfsEta: null,
  deconsolidationCfsRegion: '',

  destinationCfsCode: '',
  destinationCfsUnCode: '',
  destinationCfsName: '',
  destinationCfsEta: null,
  destinationCfsRegion: '',

  placeOfReceiptPickupFrom: '',
  placeOfReceiptPickupFromName: '',
  placeOfReceiptPickupTo: '',
  placeOfReceiptPickupToName: '',

  placeOfDeliveryCode: '',
  placeOfDeliveryUnCode: '',
  placeOfDeliveryType: '-1',
  placeOfDeliveryName: '',
  placeOfDeliveryEta: null,
  placeOfDeliveryRegion: '',

  manufacturerNames: [{ id: crypto.randomUUID(), name: '' }],

  warehouse: '',
  warehouseName: '',
  deliveryReference: '',

  cfsCutoffDate: null,
  cfsCutoffTime: '',
  gatewayCutoffDate: null,
  gatewayCutoffTime: '',

  destinationWarehouse: '',

  docDelivery: '',
  docContact: '',
  docCutoffDate: null,
  docCutoffTime: '',
  customsCutoffDate: null,
  customsCutoffTime: '',

  cargoReadDate: null,

  deliveryType: '',
  cbl: '',
  direction: '',
  cfsContactName: '',
  cfsContactPhone: '',
  customsBroker: '',
  deliveryAppointmentDateFrom: null,
  deliveryAppointmentTimeFrom: '',
  deliveryAppointmentDateTo: null,
  deliveryAppointmentTimeTo: '',
  transitTime: '',
  frequency: '',

  loadCode: '',
  loadName: '',
  loadEts: null,
  loadRegion: '',

  dischargeCode: '',
  dischargeName: '',
  dischargeEta: null,
  dischargeRegion: '',

  rampCode: '',
  rampName: '',
  rampEta: null,
  rampRegion: '',

  locationInformationPublic: "",
  locationInformationPrivate: "",
  callAccurate: true,

  loadUnCode: '',
  originUncode: '',
  dischargeUnCode: '',
  destinationUnCode: '',
  deConsolidationUNCode: '',
});

export const DEFAULT_PICKUP_FORM: PickupDetailsFormData = {
  pickupCountry: '',
  postalCodeCity: '',
  estimatedPickupDate: null,
  pickupCargoAtCode: '',
  instructions: '',
  name: '',
  streetAddress: '',
  accessorials: [],
  pickupCity: '',
  pickupZipCode: '',
  pickupState: '',
  contactName: '',
  contactPhone: '',
  contactEmail: '',
  latitude: '',
  longitude: '',
  stateCode: '',
  stateId: '',
};

export const DEFAULT_ACCESSORY_OPTIONS: AccessoriesOption[] = [
  { id: 'airport-pu', label: 'Airport PU' },
  { id: 'appointment', label: 'Appointment' },
  { id: 'cfs-delivery', label: 'CFS Delivery' },
  { id: 'cfs-pickup', label: 'CFS Pickup' },
  { id: 'hazardous-material', label: 'Hazardous Material' },
  { id: 'liftgate', label: 'Liftgate' },
  { id: 'over-length-charge', label: 'Over Length Charge' },
  { id: 'residential', label: 'Residential' },
];

export const getInitialDoorDeliveryData = (): DoorDeliveryFormData => ({
  doorDeliveryCountry: '',
  postalCodeCity: '',
  estimatedDeliveryDate: null,
  streetAddress: '',
  accessorials: [],
  doorDeliveryCity: '',
  doorDeliveryZipCode: '',
  doorDeliveryState: '',
  stackable: true,
  shipmentType: 'LTL',
  truckerCode: '',
  truckerDetails: '',
  latitude: '',
  longitude: '',
  residential: '',
  truckerName: '',
});
