import { getFormattedDate, parseApiDate } from "../../../../core/utils/date.utility";
import { num, str, strOrNull } from "../../../../core/utils/string.utility";

export function buildBookingQuoteRoutingBean(r: any, loginbean: any = {}) {
  const routing = r?.routingFormData ?? {};
  let warehouse = routing?.warehouse ? str(routing.warehouse).split(' - ') : '';

  return {
    preCarriageType: str(routing?.preCarriageType) || '-1',
    preCarriageBy: str(routing?.preCarriageBy) || '',
    bookingNo: null,
    bookingQuoteType: null,
    handlingOfficeUnCode: null,
    vesselCode: str(routing?.vesselCode),
    vessel: str(routing?.vesselName),
    voyage: str(routing?.voyage),
    warehouse: warehouse[0] || '',
    deliveryDate: getFormattedDate(routing?.cfsCutoffDate || routing?.routingFormData?.cfsCutoffDate) || "",
    deliveryTime: fmtTime(routing?.cfsCutoffTime || routing?.routingFormData?.cfsCutoffTime),
    deliveryTimeTo: null,
    originCode: str(routing?.placeOfReceiptCode),
    originName: str(routing?.placeOfReceiptName),
    loadCode: str(routing?.portOfLoadingCode),
    loadName: str(routing?.portOfLoadingName),
    dischargeCode: str(routing?.portOfDischargeCode),
    dischargeName: str(routing?.portOfDischargeName),
    destinationCode: str(routing?.placeOfDeliveryCode),
    destinationName: str(routing?.placeOfDeliveryName||routing?.portOfDischargeName),
    sailDate: getFormattedDate(routing?.portOfLoadingEts),
    etdOrigin: getFormattedDate(routing?.placeOfReceiptEtd) || "",
    etaDate: getFormattedDate(routing?.portOfDischargeEta) || "",
    documentCutoffDate: getFormattedDate(routing?.docCutoffDate || routing?.routingFormData?.docCutoffDate) || "",
    documentationCutOffTime: fmtTime(routing?.docCutoffTime || routing?.routingFormData?.docCutoffTime) ||fmtTime(routing?.cfsCutoffTime || routing?.routingFormData?.cfsCutoffTime),
    warehouseName: warehouse[1] || '',
    fromRegionCode: str(routing?.fromRegionCode) || "",
    toRegionCode: str(routing?.toRegionCode) || "",
    viaRegionCode: str(routing?.viaRegionCode) || "",
    originUncode: str(routing?.originUncode) || '',
    consolidationCFSUNCode: str(routing?.consolidationCfsUnCode) || '',
    loadUnCode: str(routing?.loadUnCode) || '',
    dischargeUnCode: str(routing?.dischargeUnCode) || '',
    destinationUnCode: str(routing?.destinationUnCode) || '',
    deConsolidationUNCode: str(routing?.deConsolidationUNCode) || '',
    finalCFSUNCode: str(routing?.destinationCfsUnCode) || '',
    placeOfDeliveryUnCode: str(routing?.placeOfDeliveryUnCode) || '',
    transshipmentPortUnCode: null,
    originRegionCode: str(routing?.placeOfReceiptRegion),
    loadRegionCode: str(routing?.portOfLoadingRegion),
    dischargeRegionCode: str(routing?.portOfDischargeRegion),
    destinationRegionCode: str(routing?.placeOfDeliveryRegion),
    deconsolidationRegionCode: str(routing?.deconsolidationCfsRegion),
    finalCFSRegionCode: str(routing?.destinationCfsRegion),
    wwaScheudle: false,
    etaDestination: getFormattedDate(routing?.placeOfDeliveryEta),
    warehouseAddress1: null,
    warehouseAddress2: null,
    warehouseAddress3: null,
    warehouseState: null,
    warehouseZipcode: null,
    warehousePhone: null,
    warehouseContact: null,
    warehouseDeliveryRef: str(routing?.deliveryReference || routing?.routingFormData?.deliveryReference) || '',
    documentDeliveryCode: str(routing?.docDelivery || routing?.routingFormData?.docDelivery) || '',
    documentDeliveryName: '',
    documentDeliveryAddress1: '',
    documentDeliveryAddress2: '',
    documentDeliveryAddress3: '',
    documentDeliveryContact: str(routing?.docContact || routing?.routingFormData?.docContact) || '',
    locationInformation: str(routing?.locationInformation) || '',
    privateLocationInformation: str(routing?.privateLocationInformation) || '',
    deConsolidationCode: str(routing?.deconsolidationCfsCode),
    deConsolidationName: str(routing?.deconsolidationCfsName),
    deConsolidationDate: getFormattedDate(routing?.deconsolidationCfsEta),
    finalCFSCode: str(routing?.destinationCfsCode),
    finalCFSName: str(routing?.destinationCfsName),
    finalCFSDate: getFormattedDate(routing?.destinationCfsEta),
    oldOriginCode: null,
    oldLoadName: null,
    consolidationCFSCode: str(routing?.consolidationCfsCode),
    consolidationCFSName: str(routing?.consolidationCfsName),
    consolidationCFSDate: getFormattedDate(routing?.consolidationCfsEtd),
    consolidationCFSRegionCode: str(routing?.consolidationCfsRegion),
    originalVesselCode: str(routing?.originalVesselCode),
    originalVesselName: str(routing?.originalVesselName),
    originalVoyage: str(routing?.originalVoyage),
    originalEts: getFormattedDate(routing?.originalEts),
    outportWarehouseCode: null,
    outportWarehouseName: null,
    placeOfReceiptOrgEtdDate: null,
    placeOfReceiptActualAtdDate: null,
    consolidationCfsOrgEtdDate: null,
    consolidationCfsActualAtdDate: null,
    portOfLoadingOrgEtsDate: null,
    portOfLoadingActualAtsDate: null,
    portOfDischargeOrgEtaDate: null,
    portOfDischargeActualAtaDate: null,
    deconsolidationCfsOrgEtaDate: null,
    deconsolidationCfsActualAtaDate: null,
    destinationCfsOrgEtaDate: null,
    destinationCfsActualAtaDate: null,
    placeOfDeliveryOrgEtaDate: null,
    placeOfDeliveryActualAtaDate: null,
    oldWarehouse: null,
    carrierBLCutoffDate: null,
    carrierBLCutOffTime: null,
    autoTitleCutoffDate: null,
    autoTitleCutOffTime: null,
    aesITNCutoffDate: null,
    aesITNCutOffTime: null,
    onCarriageType: null,
    onCarriageBy: null,
    carrierPlaceOfReceiptCode: null,
    carrierPlaceOfReceitName: null,
    carrierPlaceOfReceiptDate: null,
    carrierPlaceOfReceiptRegion: null,
    vgmCutoffDate: null,
    vgmCutOffTime: null,
    dischargCodeCountry: str(routing?.dischargCodeCountry),
    placeOfDelieveryCodeCountry: str(routing?.placeOfDelieveryCodeCountry),
    loadCodeCountry: str(routing?.loadCodeCountry),
    finalCFSCodeCountry: str(routing?.finalCFSCodeCountry),
    manufactureName: null,
    customsDeclaration: '',
    customsContact: null,
    customsCutoffDate: getFormattedDate(routing?.docCutoffDate || routing?.routingFormData?.docCutoffDate),
    customsCutoffTime: fmtTime(routing?.docCutoffTime || routing?.routingFormData?.docCutoffTime),
    carrierPlaceOfDeliveryCode: null,
    carrierPlaceOfDeliveryName: null,
    carrierPlaceOfDeliveryDate: null,
    carrierPlaceOfDeliveryRegion: null,
    carrierCode: routing?.carrierCode?.split('-')[0].trim() || null,
    terms: strOrNull(routing?.termsCode || routing?.routingFormData?.termsCode),
    termName: strOrNull(routing?.termsLabel || routing?.routingFormData?.termsLabel),
    transitDays: null,
    validUntil: null,
    clauses: null,
    cargoValue: null,
    notes: null,
    quoteNumber: 0,
    rowId: null,
    rowNumber: 0,
    notes2: null,
    notes3: null,
    notes4: null,
    notes5: null,
    carriers: null,
    bookingQuoteChargeBeanList: [],
    ratingType: null,
    deliveryAppointmentDateFrom: null,
    deliveryAppointmentDateTo: null,
    deliveryAppointmentTimeFrom: null,
    deliveryAppointmentTimeTo: null,
    warehouseLatitude: null,
    warehouseLongitude: null,
    warehouseAddressForLatLong: null,
    manufacturerDetailBeans: (routing?.manufacturerNames || routing?.routingFormData?.manufacturerNames || []).map((m: any) => ({
      manufacturerName: str(m.name),
    })),
    oldVesselCode: str(routing?.oldVesselCode),
    oldVesselName: str(routing?.oldVesselName),
    oldVoyage: str(routing?.oldVoyage),
    cfsContactNameChinese: null,
    cfsContactNameEnglish: null,
    cfsContactPhone: null,
    oldIncoTerms: null,
    incoTerms: null,
    placeOfReceiptName1: str(routing?.placeOfReceiptPickupFrom),
    placeOfReceiptName2: str(routing?.placeOfReceiptPickupFromName),
    placeOfReceiptName3: str(routing?.placeOfReceiptPickupTo),
    placeOfReceiptName4: str(routing?.placeOfReceiptPickupToName),
    placeOfDeliveryName1: str(routing?.placeOfDeliveryName),
    placeOfDeliveryName2Selection: str(routing?.placeOfDeliveryType),
    preCarriageETS: getFormattedDate(routing?.preCarriageEts),
    transitTime: strOrNull(routing?.transitTime),
    carrierList: null,
    frequency: str(routing?.frequency || ''),
    isPrintSailingScheduleInConfirmationDocument: str(routing?.isPrintSailingScheduleInConfirmationDocument),
    gatewayCutoffDate: getFormattedDate(routing?.gatewayCutoffDate),
    gatewayCutoffTime: fmtTime(routing?.gatewayCutoffTime),
    portToPortCo2Emission: null,
    manufacturerDetailBean: routing?.manufacturerDetailBean ?? {}
  };
}

const fmtTime = (v: any): string => str(v).replace(/\s+([AaPp][Mm])$/, '$1');

export function buildTransshipmentRoutingBeanList(r: any, moduleType: any) {
  const ports = r?.routingFormData?.transshipmentPorts || [];
  if (ports.length === 0) {
    return [
      {
        referenceNumber: '',
        moduleCode: moduleType,
        transshipmentPortSeq: 0,
        transshipmentPortCode: null,
        transshipmentPortName: null,
      },
    ];
  }

  return ports.map((p: any, idx: number) => ({
    referenceNumber: '',
    moduleCode: moduleType,
    transshipmentPortSeq: p.id,
    transshipmentPortCode: str(p.portCode),
    transshipmentPortName: str(p.portName),
  }));
}

export const mapRoutingFromPopulate = (mainBookingQuoteBean: any) => {
  const quoteBean = mainBookingQuoteBean?.bookingQuoteBean;
  const r = quoteBean?.bookingQuoteRoutingBean;
  const transshipmentRoutingBeanList = mainBookingQuoteBean?.transshipmentRoutingBeanList;
  const doorDeliveryDetailsBean = mainBookingQuoteBean?.doorDeliveryDetailsBean;

  if (!r) return {};
  const rawPickup = quoteBean?.pickupNeeded;
  const pickupNeeded =   rawPickup === 'F' ? 'N' : (rawPickup ?? 'N');
  return {
    pickupNeeded,
    terms: quoteBean?.terms ?? '',
    termsLabel: quoteBean?.termName || quoteBean?.terms || '',
    deliveryType: quoteBean?.cfsDeliveryType ?? '',
    preCarriageType: r.preCarriageType ?? '',
    preCarriageBy: r.preCarriageBy ?? '',
    preCarriageEts: parseApiDate(r.preCarriageETS),
    vesselCode: r.vesselCode ?? '',
    vesselName: r.vessel ?? '',
    voyage: r.voyage ?? '',
    carrierCode: quoteBean?.lineCode ?? '',
    placeOfReceiptCode: r.originCode ?? '',
    placeOfReceiptName: r.originName ?? '',
    placeOfReceiptEtd: parseApiDate(r.etdOrigin),
    placeOfReceiptRegion: r.originRegionCode ?? '',
    placeOfReceiptPickupFrom: r.placeOfReceiptName1 ?? '',
    placeOfReceiptPickupFromName: r.placeOfReceiptName2 ?? '',
    placeOfReceiptPickupTo: r.placeOfReceiptName3 ?? '',
    placeOfReceiptPickupToName: r.placeOfReceiptName4 ?? '',
    consolidationCfsCode: r.consolidationCFSCode ?? '',
    consolidationCfsName: r.consolidationCFSName ?? '',
    consolidationCfsEtd: parseApiDate(r.consolidationCFSDate),
    consolidationCfsRegion: r.consolidationCFSRegionCode ?? '',
    portOfLoadingCode: r.loadCode ?? '',
    portOfLoadingName: r.loadName ?? '',
    portOfLoadingEts: parseApiDate(r.sailDate),
    portOfLoadingRegion: r.loadRegionCode ?? '',
    transshipmentPorts: mapTransshipmentPorts(
      transshipmentRoutingBeanList
    ),
    portOfDischargeCode: r.dischargeCode ?? '',
    portOfDischargeName: r.dischargeName ?? '',
    portOfDischargeEta: parseApiDate(r.etaDate),
    portOfDischargeRegion: r.dischargeRegionCode ?? '',
    deconsolidationCfsCode: r.deConsolidationCode ?? '',
    deconsolidationCfsName: r.deConsolidationName ?? '',
    deconsolidationCfsEta: parseApiDate(r.deConsolidationDate),
    deconsolidationCfsRegion: r.deconsolidationRegionCode ?? '',
    destinationCfsCode: r.finalCFSCode ?? '',
    destinationCfsName: r.finalCFSName ?? '',
    destinationCfsEta: parseApiDate(r.finalCFSDate),
    destinationCfsRegion: r.finalCFSRegionCode ?? '',
    placeOfDeliveryCode: r.destinationCode ?? '',
    placeOfDeliveryType: r.placeOfDeliveryName2Selection ?? '',
    placeOfDeliveryName: r.placeOfDeliveryName1 ?? '',
    placeOfDeliveryEta: parseApiDate(r.etaDestination),
    placeOfDeliveryRegion: r.destinationRegionCode ?? '',
    manufacturerNames: mapManufacturerNames(r.manufacturerDetailBeans),
    warehouse: r.warehouse + (r.warehouseName ? ` - ${r.warehouseName}` : ''),
    warehouseName: r.warehouseName ?? '',
    fromRegionCode: r.fromRegionCode ?? '',
    toRegionCode: r.toRegionCode ?? '',
    viaRegionCode: r.viaRegionCode ?? '',
    destinationWarehouse: doorDeliveryDetailsBean.destinationWarehouse ?? '',
    deliveryReference: r.warehouseDeliveryRef ?? '',
    deliveryDate: r.deliveryDate,
    cargoReadDate: parseApiDate(r.deliveryDate),
    cfsCutoffDate: parseApiDate(r.deliveryDate),
    cfsCutoffTime: r.deliveryTime ?? '',
    gatewayCutoffDate: parseApiDate(r.gatewayCutoffDate),
    gatewayCutoffTime: r.gatewayCutoffTime ?? '',
    docDelivery: r.documentDeliveryCode ?? '',
    docContact: r.documentDeliveryContact ?? '',
    docCutoffDate: parseApiDate(r.documentCutoffDate),
    docCutoffTime: r.documentationCutOffTime ?? '',
    locationInformation: r.locationInformation,
    privateLocationInformation: r.privateLocationInformation,
    destinationUnCode: r.destinationUnCode,
    dischargeUnCode: r.dischargeUnCode,
    loadUnCode: r.loadUnCode,
    originCode: r.originCode,
    originName: r.originName,
    originUncode: r.originUncode,
    transitTime: r.transitTime != null ? String(r.transitTime) : '',
    frequency: r.frequency ?? '',
    originalVesselCode: r.originalVesselCode ?? '',
    originalVesselName: r.originalVesselName ?? '',
    originalVoyage: r.originalVoyage ?? '',
    originalEts: r.originalEts ?? '',
    dischargCodeCountry: r.dischargCodeCountry ?? '',
    placeOfDelieveryCodeCountry: r.placeOfDelieveryCodeCountry ?? '',
    loadCodeCountry: r.loadCodeCountry ?? '',
    finalCFSCodeCountry: r.finalCFSCodeCountry ?? '',
    oldVesselCode: r.oldVesselCode ?? '',
    oldVesselName: r.oldVesselName ?? '',
    oldVoyage: r.oldVoyage ?? '',
    isPrintSailingScheduleInConfirmationDocument: r.isPrintSailingScheduleInConfirmationDocument ?? '',
    manufacturerDetailBean: r.manufacturerDetailBean ?? {},
  };
};

const mapTransshipmentPorts = (list: any[] | null) =>
 (list ?? []).map((r: any, i: number) => ({
    id: r.transshipmentPortSeq || i,
    portCode: r.transshipmentPortCode ?? '',
    portName: r.transshipmentPortName ?? '',
    eta: parseApiDate(r.transshipmentPortDate ?? null),
  }));

const mapManufacturerNames = (bean: any) =>
  (bean ?? []).map((m: any) => ({ name: m.manufacturerName ?? '', id: m.manufacturerDetailId ?? '' }));

const normalizeCarrierCode = (val: any) => {
  const v = str(val);
  if (v.includes(' - ')) {
    return v.split(' - ')[0].substring(0, 10);
  }
  return v.substring(0, 10);
};