export interface DocumentUploadFormData {
    genericReference?: string;
    documentId?: number;
    referenceNumber?: string;
    referenceObject?: string;
    documentFileId?: string;
    documentTypeId?: number;
    documentFileName?: string;
    documentType: string;
    documentTypeName?: string;
    documentReferenceNumber: string;
    documentRequiredDate: string;
    documentRequiredTime: string;
    documentReceivedDate: string;
    documentReceivedTime: string;
    documentExpirationDate: string;
    documentCustomsOffice: string;
    channel: string;
    documentCarrier?: string;
    documentShipper:  string;
    documentComments?: string;
    documentMode?: string;
    recordOrder?: number;
    status?: number;
    schemaId?: string;
    officeId?: string;
    inputUser?: string;
    inputDate?: string;
    updateUser?: string;
    updateDate?: string;
    inputLdapUser?: string;
    updateLdapUser?: string;
    filePath?: string;
    contentType?: string;
    genFileBeans?: any;
    transactionalFlag?: string;
    agent: string;
    comments: string;
    documentTypeHardcopyOnly?: string;
    documentReceivedStatus?: string;
    inputUserFullName?: string;
    oldRecordOrder?: number;
    fileUploaded?: boolean;
    imageSource?: string;
    active: string;
    documentCreationFromFileBean?: any;
    selectedPages?: any;
    eserviceUploadFlag?: string;
    eserviceUploadApproval?: string;
    oldDocumentReferenceNumber?: string;
    oldDocumentType?: string;
    requiredByDate?: string;
    requiredByTime?: string;
    isActive?: boolean;
    iEmailSentCount?: number;
    moduleName?: string;
    documentHistoryId?: string;
    pickupId?: string;
    warehouseName?: string;
    documentChannel?: string;
    eServiceUploadFlag?: string;
    commonBean?: any;
    fileUploadKey?: string;
    uploadedFrom?: string;
    mandatory?: boolean;
    officeMandatoryDocument?: boolean;
    uploadFromEservice?: boolean;
    systemAddedDocument?: boolean;
    uploadThroughAPI?: boolean;
    uploadFromBkgApi?: boolean;
    fromSplitDocument?: boolean;
    customRefchanged?: boolean;
    uploadDocumentsType?: string;
    transactionFlagStatus?: string;
    readyForUpload?: boolean;
    hardcopyPending?: boolean;
    pngDocument?: boolean;
    updateDocument?: boolean;
    hardcopyOnly?: boolean;
    documentReceived?: boolean;
}

export const createDefaultDocumentRows = (): DocumentUploadFormData[] => ([
    {
        documentType: "",
        documentReferenceNumber: "",
        documentRequiredDate: "",
        documentRequiredTime: "",
        documentReceivedDate: "",
        documentReceivedTime: "",
        documentExpirationDate: "",
        documentCustomsOffice: "",
        channel: "",
        documentCarrier: "",
        documentShipper: "",
        agent: "",
        comments: "",
        active: "Yes",
        fileUploadKey: undefined,
    },
]);