export const AirToggleKeys = {
  PHX_COMMON_VAT_UTIL_AIR: 'PHX_COMMON_VAT_UTIL_AIR',
  AIR_AWB_COUNTRY_BUTTON_DEFAULT_NAME: 'AIR_AWB_COUNTRY_BUTTON_DEFAULT_NAME',
  AIR_WAREHOUSE_BKG_STAT_REPORT_ENABLED: 'AIR_WAREHOUSE_BKG_STAT_REPORT_ENABLED',
  AIR_BKG_MODIFY_HANDLING_DIMENSION_FOR_TMS: 'AIR_BKG_MODIFY_HANDLING_DIMENSION_FOR_TMS',
} as const;

export type AirToggleKey = typeof AirToggleKeys[keyof typeof AirToggleKeys];
