export const EIToggleKeys = {
  TRK_INTEGRATION_TOGGLE_MIGRATION: 'TRK_INTEGRATION_TOGGLE_MIGRATION',
  OCEAN_ARN_FREIGHT_RELEASE_DOC_TRANSMISSION: 'OCEAN_ARN_FREIGHT_RELEASE_DOC_TRANSMISSION',
  ARRIVED_AT_DECONSOLIDATION_AUTO_EMAIL_THIRD_PARTY: 'ARRIVED_AT_DECONSOLIDATION_AUTO_EMAIL_THIRD_PARTY',
  ARRIVED_AT_DECONSOLIDATION_TRANSMIT_TO_SHIPCO: 'ARRIVED_AT_DECONSOLIDATION_TRANSMIT_TO_SHIPCO',
} as const;

export type EIToggleKey = typeof EIToggleKeys[keyof typeof EIToggleKeys];
