import { RoutingFormData } from 'phoenix-common-react';

export const initialFormData: RoutingFormData = {
  terms: '',
  pickupNeeded: 'N',
  preCarriageType: '',
  preCarriageBy: '',
  preCarriageEts: null,
  vesselCode: '',
  vesselName: '',
  voyage: '',
  carrierCode: '',
  placeOfReceiptCode: '',
  placeOfReceiptName: '',
  placeOfReceiptEtd: null,
  placeOfReceiptRegion: '',
  consolidationCfsCode: '',
  consolidationCfsName: '',
  consolidationCfsEtd: null,
  consolidationCfsRegion: '',
  portOfLoadingCode: '',
  portOfLoadingName: '',
  portOfLoadingEts: null,
  portOfLoadingRegion: '',
  transshipmentPorts: [
    { id: 1, portCode: '', portName: '', eta: null },
  ],
  portOfDischargeCode: '',
  portOfDischargeName: '',
  portOfDischargeEta: null,
  portOfDischargeRegion: '',
  deconsolidationCfsCode: '',
  deconsolidationCfsName: '',
  deconsolidationCfsEta: null,
  deconsolidationCfsRegion: '',
  destinationCfsCode: '',
  destinationCfsName: '',
  destinationCfsEta: null,
  destinationCfsRegion: '',
  placeOfReceiptPickupFrom: '',
  placeOfReceiptPickupFromName: '',
  placeOfReceiptPickupTo: '',
  placeOfReceiptPickupToName: '',
  placeOfDeliveryCode: '',
  placeOfDeliveryType: '',
  placeOfDeliveryName: '',
  placeOfDeliveryEta: null,
  placeOfDeliveryRegion: '',
  manufacturerNames: [{ id: crypto.randomUUID(), name: '' }],
  warehouse: '',
  deliveryReference: '',
  cfsCutoffDate: null,
  cfsCutoffTime: '',
  gatewayCutoffDate: null,
  gatewayCutoffTime: '',
  destinationWarehouse: '',
  docDelivery: '',
  docContact: '',
  docCutoffDate: null,
  docCutoffTime: '',
  cargoReadDate: null,
  deliveryType: '',
};
